ESGF/esg-publisher

src/python/esgcet/esgcet/publish/facetSplitter.py

@sashakames 
I think that for the planned feature of multi-valued facets it would be good to allow for fairly arbitrary separators so as to increase flexibility to avoid the separator conflicting with anything in the component strings. Hence this new module that implements it.
This module does not refuse to split on a character just because that character might cause problems elsewhere, but obviously if someone put pipe symbols into a facet intended to form part of the dataset ID then it would cause issues at the mapfile stage before the splitter even gets run.
Regards,
Alan

add splitter for multi-valued facets

---

src/python/esgcet/esgcet/config/etc/template.ini
src/python/esgcet/esgcet/publish/utility.py

Gives node managers a way to turn off colours by setting esg.ini variable `disable_colors = True` (in section `[DEFAULT]`). Defaults to false (i.e. colours permitted) if not set.
Depending on the terminal settings, the colours might not be helpful, and might make the text illegible. Example:

Allow disable colours

---

src/python/esgcet/esgcet/config/cmip6_handler.py

Correct typo `defaut` -> `default`.

correct typo in keyword argument in code

---

src/python/esgcet/esgcet/config/cmip6_handler.py
src/python/esgcet/esgcet/config/registry.py
src/python/esgcet/esgcet/publish/utility.py
src/python/esgcet/scripts/esgpublish

add functionality to pass extra args to the handler where the handler supports them, and actually pass a "handler" arg (boolean) based on whether --set-replica is set, and add support for it in CMIP6 handler so that it suppresses calling PrePARE

prevent calling PrePARE for CMIP6 in replicas

---

src/python/esgcet/esgcet/config/cmip6_handler.py

PrePARE call in ``cmip6_handler.py`` needs changes according to CMOR 3.3.1. Fake args are useless now.

Simplifies call to PrePARE 3.3.1 + cleanup code

---

src/python/esgcet/esgcet/publish/cim.py

a token that was meant to be substituted had got left in as literal - fixing

report name of top_dir in CIM error

---

src/python/esgcet/scripts/esgpublish
src/python/esgcet/scripts/esgunpublish

Sets `restApi` to:
* default True in `esgpublish`,
* default False in `esgunpublish` but with a help message alerting that this is intended to change (per #74)
and adds command line flag `--hessian-api`
Order of precedence is:
* command-line option (`--rest-api` or `--hessian-api`)
* if not specified, `use_rest_api` in default
* if not set, use default value (per above)
Fixes a problem in existing code in esgpublish that had `restApi=True` at the top, and no way to override it except by editing the code.
**Warning**: untested, although it looks like it should straightforwardly work. Please treat the diff as a suggestion.

change logic over whether to use REST api

---

src/python/esgcet/esgcet/publish/extract.py
src/python/esgcet/esgcet/publish/utility.py
src/python/esgcet/scripts/esgpublish

Add a new command line option `--commit-every n` that will cause the publisher to commit file info to the database after every `n` files when scanning files.
This reduces memory consumption when publishing datasets with a large number of files, since information about each file is not held in memory throughout the whole publication.
Existing behaviour is preserved if the option is not given.

Add --commit-every flag to control how often to commit to DB when scanning files

---

docs/configuration.rst
src/python/esgcet/esgcet/publish/utility.py
src/python/esgcet/scripts/esgunpublish

If set to true, aggregations are not created. By default it is set to false which preserves existing behaviour.
We have a project where aggregations are not required, and skipping the aggregation step saves a considerable amount of time during publication.

Add 'skip_aggregations' option in project specific config file

---

src/python/esgcet/esgcet/config/cmip6_handler.py
src/python/esgcet/esgcet/publish/__init__.py
src/python/esgcet/esgcet/publish/utility.py

1) Add option `force_validation` in `[config:<project>]` section, to force CMOR even if dataset is replica or has already passed CMOR.  (Default=False.)
2) Add option `cmor_table_subdirs` in `[config:<project>]` section, to treat the specified `cmor_table_path` as a directory containing (read-only) subdirectories for each table version.  These should be fetched using `esgfetchtables` (in esgprep).  If set to False (the default), the existing behaviour is retained, where the `cmor_table_path` points to a git clone.
3) When using a git clone (`cmor_table_subdirs=False`), check the return status of 'git' commands, and raise an exception if they fail.

CMOR tables related changes (for CMIP6)

---

src/python/esgcet/esgcet/publish/wrappers.py
src/python/esgcet/esgcet/ui/extraction_controls.py
src/python/esgcet/scripts/esgadd_facetvalues
src/python/esgcet/scripts/esgcopy_files
src/python/esgcet/scripts/esgfind_excludes
src/python/esgcet/scripts/esglist_datasets
src/python/esgcet/scripts/esglist_files
src/python/esgcet/scripts/esgpublish
src/python/esgcet/scripts/esgscan_directory
src/python/esgcet/scripts/esgsetup
src/python/esgcet/scripts/esgtest_publish
src/python/esgcet/scripts/esgunpublish
src/python/esgcet/scripts/esgupdate_metadata

Use `[DEFAULT]` instead of `[extract]` section of esg.ini file for logging-related variables for most commands.
(It looks like a line of code, which uses 'extract', was copied from esgextract to the other scripts.
This commit leaves it as 'extract' in esgextract and changes it in everything else.)

Use [DEFAULT] section of esg.ini file for logging related vars

---

docs/configuration.rst
src/python/esgcet/esgcet/config/etc/template.ini
src/python/esgcet/esgcet/publish/thredds.py

Work between European centres regarding a load-balanced arrangement for CDS is going to require certain data nodes to have deterministic paths for the THREDDS catalogues, so that the same dataset can be published independently in multiple sites and have the local part of the URL be the same at each site.  This means adding an option to avoid the numbered subdirectories, which cannot be predicted.
This pull request adds a (non-default) functionality to allow the THREDDS catalogue location to be based on the dataset name, for example (relative to the THREDDS content root):
`esgcet/specs/output/KNMI/EC-EARTH2/seaIceInit/S19381101/mon/ocean/Omon/msftmyz/r10i1p1/specs.output.KNMI.EC-EARTH2.seaIceInit.S19381101.mon.ocean.Omon.msftmyz.r10i1p1.v1.xml`
in place of something like: …

option to allow deterministic THREDDS catalog paths

---

src/python/esgcet/scripts/esgpublish

At line 654 the list of dataset names and versions from a single map
file are sorted.  However, since the `esgmapfile` tool generates a
separate map file for each unique dataset and version by default [1],
this won't have any effect in sorting multiple versions of a given
dataset.  Instead the sort has to occur when walking the map file tree
so that map files with the same base filename (ie. dataset ID) but
different versions are ingested in the correct version order.  Given
that `os.walk()` uses `readdir()` the results aren't guaranteed to
be in any specific order and therefore need to be explicitly sorted.
[1] https://github.com/ESGF/esgf-prepare/blob/v2.9.3/esgprep/esgmapfile.py#L80

Process map files in consistent order

---

src/python/esgcet/esgcet/publish/utility.py

Fixes #133.
The reason `$HOME/.globus/certificates` is always returned is because the bare `except` catches the `NameError` for `config` not being defined.
Ideally, the bare `except` should be replaced with a more specific `except` catching only the exception(s) that are raised when a config item is missing.

Fix retrieval of hessian cert location

---

src/python/esgcet/esgcet/config/project.py
src/python/esgcet/esgcet/publish/utility.py

Moves from the handler base class in .project to utility where we can iterate over the files prior to extraction

move validateFile to validate all files

---

src/python/esgcet/esgcet/config/cmip6_handler.py

Support a configuration option in CMIP6 handler (`skip_validation` in `[config:cmip6]` section of `esg.ini`), to skip PrePARE.
This is to allow sites to optimise by skipping PrePARE in the publisher where they are already running PrePARE separately outside of the publisher.
We do not need to advertise this option if there is any concern about it being abused for purpose of completely avoiding running PrePARE.

add option to skip PrePARE

---

pkg/esgcet/mapfile.py
pkg/esgcet/mk_dataset.py

Changes based on review of code by @alaniwi and I. Addresses the issue of normalize_path method not respecting data roots from the ini file, which may be important for generating the correct paths for search.
e.g. In the old method, the path `/alldata/cordex/data/cordex/files/somefile.nc`, with data roots `{"/alldata/cordex/data": "esg_cordex"}`
would be normalized as `("cordex/data/cordex/files/somefile.nc", "/alldata")`, rather than `("cordex/files/somefile.nc", "/alldata/cordex/data")`

Refactor normalize_path to respect data roots from ini

---

docs/whatsnew.rst
pkg/esgcet/args.py
pkg/esgcet/cmip6.py

The `skip_prepare` setting is currently used to skip PrePARE for replicas but it is always enforced for the primary copy. This PR changes the behavior so that it applies to **non**-replicas, and also adds a `force_prepare` option for replicas, in order to make it more analogous to the `skip_validation` and `force_validation` options used in the existing publisher.
See the changes to the release notes file below for more info.
(See [here](https://github.com/ESGF/esg-publisher/blob/master/src/python/esgcet/esgcet/config/cmip6_handler.py#L52-L79) for the existing behavior.  NB the existing `force_validation` also overrides the check as to whether a suitable `cmor_version` attribute already exists in the file metadata, but that check does not seem to exist in the refactored publisher.)
We …

Change use of skip_prepare and add force_prepare

---

src/python/setup.py

Idea is to simplify the 'setup.py' by just using an additional list of to-be-added dependencies in case the 'make_config' is to be done. Call to `setup()` is made only once.
Not sure what is really needed. It's just an example.

Only call setup once.

---

src/python/esgcet/pub_client.py
src/python/esgcet/xmlfix.py

input4MIPs data from UoM would not publish - it turns out that it was constructing invalid XML in the payload, containing an `&` sign found in the netCDF global attribute `source` which was not part of a valid entity (value contains the substring `"NOAA & AGAGE networks"`).  This commit will cause this to be changed to `&amp;`, while also trying to preserving any ampersands which are already part of HTML entities.  With this tweak, the data is now publishable.
@sashakames Note that I have forked from 5.2.4.  I attempted to fork from the HEAD of `v5.2.5-proj` but that seems to not be working at the moment.  I think that my changes are orthogonal to whatever you are working on there, and should be easily merged when needed.

tweak bad XML in payload, in particular using & -> &amp;
